# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

shared: &shared
    steps:
      - checkout
      - run:
            name: Prepare environment
            command: |
                apt-get update
                apt-get -y full-upgrade
      - run:
            name: Install dependencies
            command: |
                apt-get install -y g++ cmake uuid-dev libboost-program-options-dev libboost-filesystem-dev libssl-dev debhelper dkms
      - run:
            name: Build blksnap-dkms package
            working_directory: pkg/deb/blksnap-dkms
            command: ./build.sh
      - run:
            name: Build blksnap-tools package
            working_directory: pkg/deb/blksnap-tools
            command: ./build.sh
      - run:
            name: Build blksnap-dev package
            working_directory: pkg/deb/blksnap-dev
            command: ./build.sh
      - run:
            name: Build blksnap-tests package
            working_directory: pkg/deb/blksnap-tests
            command: ./build.sh
      - run:
            name: Save generate packages as artifacts
            working_directory: build
            command: |
                mkdir /tmp/artifacts
                mv *.deb /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

jobs:
    debian11:
        <<: *shared
        docker:
            - image: library/debian:bullseye

    debian12:
        <<: *shared
        docker:
            - image: library/debian:bookworm

workflows:
  build-install:
    jobs:
      - debian11
      - debian12