#!/bin/sh
set -e

checkModule()
{
	if ! lsmod | grep "$1" > /dev/null
	then
		return 1
	fi
	return 0
}

case "$1" in
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|purge)
		if [ -e "/dev/blksnap" ]
		then
			rmmod blksnap || true
		fi
		if [ -e "/dev/veeamblksnap" ]
		then
			rmmod veeamblksnap || true
		fi
		if ! lsmod | grep "/dev/bdevfilter" > /dev/null
		then
			if [ -e /sys/kernel/livepatch/bdevfilter/enabled ]
			then
				echo 0 > /sys/kernel/livepatch/bdevfilter/enabled || true
				while [ -e /sys/kernel/livepatch/bdevfilter/enabled ]
				do
					sleep 1s
				done
			fi
			rmmod bdevfilter || true
		fi
	;;
	*)
		echo "prerm called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0
